name: Run Tests and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: npm ci

      - name: Run Lint
        working-directory: ${{ matrix.dir }}
        run: npm run lint

      - name: Run Tests
        working-directory: ${{ matrix.dir }}
        run: npm test
